### ISSUE TITLE
Bug: Pock will reverse the settings of the touch bar

### ISSUE THREAD

**Issue by quericy** [pock/pockkit#2]
The system setting of the touch bar:
+ TouchBar display: `F1/F2...`
+ Press FN to display: `show app control`

When I double press Control key to toggle between Pock to system touch bar, and double press the Control key to switch back, the settings of the touch bar will be reverse:
+ TouchBar display: `show app control`
+ Press FN to display: `F1/F2...`

**Comment by pigigaldi** [comment]
PockKit is a framework for building Pock widgets. This type of bug report must be created on Pock dedicated [repo](https://github.com/pock/pock).
